# Generated by Django 3.1.7 on 2021-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anliuuid', models.CharField(default='', max_length=100)),
                ('Subject', models.CharField(default='', max_length=200)),
                ('rightAnswer', models.CharField(default='', max_length=100)),
                ('wrongAnswer1', models.CharField(default='', max_length=100)),
                ('wrongAnswer2', models.CharField(default='', max_length=100)),
                ('wrongAnswer3', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
